### ISSUE TITLE
Running tests with 0.5.15 command line tool throws an exception

### ISSUE THREAD

**Issue by nieve** [machine/machine.specifications#161]
I'm trying to run the 0.5.15 mspec.exe (as well as the mspec-clr4.exe) on the command line to run some tests and I am getting the following error:

Runner failure: System.MissingMethodException: Constructor on type 'Machine.Specifications.Runner.Impl.DefaultRunner' not found.
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at Machine.Specifications.Runner.Impl.AppDomainRunner.CreateRunnerInSeparateAppDomain(AppDomain appDomain, Assembly assembly)
Constructor on type 'Machine.Specifications.Runner.Impl.DefaultRunner' not found

Running the same tests with the 0.5.12 version has no issues.

**Comment by mikeblakeuk** [comment]
I'm now getting this on my Team City Agent
plugins\dotnetPlugin\bin\JetBrains.BuildServer.NUnitLauncher.exe #TeamCityImplicit
Runner failure: System.MissingMethodException: Constructor on type 'Machine.Specifications.Runner.Impl.DefaultRunner' not found.

Machine.Specifications.Runner.Utility.dll 0.9.0.0
Machine.Specifications.dll 0.9.1.0
Machine.Specifications.Clr4.dll 0.9.1.0
Any ideas?
Thanks

**Comment by agross** [comment]
TeamCity's plugin was likely never updated to support the new runner in 0.9. Run mspec as a Command Line build step instead.

**Comment by mikeblakeuk** [comment]
Note this is working with 0.8.3

**Comment by agross** [comment]
AFAIK @danielmarbach released 0.9 with the breaking changes for the runner.

**Comment by danielmarbach** [comment]
Indeed I did. I didn't know that there is a separate runner for TC
