### ISSUE TITLE
Using null-conditional-operator ?. breaks tests

### ISSUE THREAD

**Issue by toebens** [machine/machine.specifications#357]
Hi,
we have multiple test that are using the same behavorConfig.
```      
private static OnCleanup onCleanup = (subject) =>
        {
            _httpContext.Request.InputStream.Dispose();
            _httpContext.Response.OutputStream.Dispose();
        };
```

When using the [null-conditional-parameter](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-conditional-operators) ".?" like this:

```     
private static OnCleanup onCleanup = (subject) =>
        {
            _httpContext?.Request?.InputStream?.Dispose();
            _httpContext?.Response?.OutputStream?.Dispose();
        };
```

This breaks our tests when running all of them (not in parallel) with the message:
```     
Machine.Fakes.Internal.InstanceCreationException: Unable to create an instance of type HttpContextBase.
Please check that the type has at least a single public constructor.
   at Machine.Fakes.Internal.AutoFakeContainer.AssertPublicConstructors(Type type)
   at Machine.Fakes.Internal.AutoFakeContainer.GetBestFitConstructor(Type type)
   at Machine.Fakes.Internal.AutoFakeContainer.CreateInstance(Type type, Stack`1 buildStack)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Machine.Fakes.Internal.AutoFakeContainer.CreateInstance(Type type, Stack`1 buildStack)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Machine.Fakes.Internal.AutoFakeContainer.CreateInstance(Type type, Stack`1 buildStack)
   at Machine.Fakes.Internal.AutoFakeContainer.CreateSubject[TSubject]()
   at Machine.Fakes.Sdk.SpecificationController`1.get_Subject()
   at Machine.Fakes.Sdk.SpecificationController`1.EnsureSubjectCreated()
```     

When executing a test one at a time they work.
How comes?

**Comment by robertcoltheart** [comment]
Can you please provide a more complete set of code that reproduces the above? I also can't tell which flavor of Fakes you're using from the above.
