### ISSUE TITLE
System.MissingMethodException when an abstract class inherits class which implements IAssemblyContext

### ISSUE THREAD

**Issue by niclasahlqvist** [machine/machine.specifications#387]
When AssemblyRunner invokes OnAssemblyStart via reflection on an abstract class instance an exception is thrown. Only concrete implementations of IAssemblyContext should have its OnAssemblyStart method invoked

#[error]Error: Machine Specifications Visual Studio Test Adapter - Fatal error while executing test.
 ##[error]System.MissingMethodException: Cannot create an abstract class.
 ##[error] at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
 ##[error] at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
 ##[error] at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
 ##[error] at System.Activator.CreateInstance(Type type, Boolean nonPublic)
 ##[error] at System.Activator.CreateInstance(Type type)
 ##[error] at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()

**Comment by niclasahlqvist** [comment]
I have fix which excludes abstract types when scanning for implementations of IAssemblyContext which I'll make a PR for.
