### ISSUE TITLE
Visual Studio 2019 Live Unit Testing isn't discovering tests

### ISSUE THREAD

**Issue by aligneddev** [machine/machine.specifications#413]
I've enjoyed using mspec and the setup for those tests. I use of mix of them and standard unit tests with MsTest. The test explorer and our build runs without problems

However, they live unit test runner doesn't run them. The same thing is happening when I right click in the .cs source code and click Debug Tests.

I'm getting this error message in the VS Output > Tests
Machine Specifications Visual Studio Test Adapter - Error while discovering specifications in assembly C:\chr\git\PrepaidRenewalService\Source\.vs\CHR.Prepaid.RenewalService\v16\lut\0\t\CHR.Prepaid.Renewal.AutoRenewalConsumer.UnitTests\Debug\netcoreapp3.1\CHR.Prepaid.Renewal.AutoRenewalConsumer.UnitTests.dll.
Mono.Cecil.Cil.SymbolsNotFoundException: No symbol found for file: C:\chr\git\PrepaidRenewalService\Source\.vs\CHR.Prepaid.RenewalService\v16\lut\0\t\CHR.Prepaid.Renewal.AutoRenewalConsumer.UnitTests\Debug\netcoreapp3.1\CHR.Prepaid.Renewal.AutoRenewalConsumer.UnitTests.dll
   at Mono.Cecil.Cil.DefaultSymbolReaderProvider.GetSymbolReader(ModuleDefinition module, String fileName)
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(Disposable`1 stream, String fileName, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Mono.Cecil.AssemblyDefinition.ReadAssembly(String fileName, ReaderParameters parameters)
   at Machine.VSTestAdapter.Discovery.BuiltIn.SourceCodeLocationFinder.LoadAssembly(String assemblyFilePath)
   at Machine.VSTestAdapter.Discovery.BuiltIn.SourceCodeLocationFinder.<>c__DisplayClass1_0.<.ctor>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Machine.VSTestAdapter.Discovery.BuiltIn.SourceCodeLocationFinder.get_Assembly()
   at Machine.VSTestAdapter.Discovery.BuiltIn.SourceCodeLocationFinder.Dispose()
   at Machine.VSTestAdapter.Discovery.BuiltIn.TestDiscoverer.DiscoverTests(String assemblyPath)
   at Machine.VSTestAdapter.Discovery.BuiltIn.BuiltInSpecificationDiscoverer.DiscoverSpecs(String assemblyFilePath)
   at Machine.VSTestAdapter.MSpecTestAdapterDiscoverer.DiscoverTests(IEnumerable`1 sources, Settings settings, IMessageLogger logger, Action`1 discoverySinkAction)

I have VS 16.8.0 Preview 1.0, but it hasn't been working for me for at least all of 2020.

Here are my nuget packages.
![image](https://user-images.githubusercontent.com/1636977/90162341-178af800-dd5a-11ea-95df-8c487de89c4c.png)

I apologize, that I haven't tried to reproduce it in a separate solution. My current solution has about 20 projects, 5 of them different unit test projects and 380 or so tests.

Do you need additional information?

Thank you,

Kevin

**Comment by robertcoltheart** [comment]
It sounds like MSpec can't find your PDB files. Can you check the output location, and also that you're using Portable format for your PDBs?

![image](https://user-images.githubusercontent.com/13191652/90201166-a5272000-de0c-11ea-8689-34e36d20b1bc.png)

**Comment by aligneddev** [comment]
Thanks for the response.

I have 
![image](https://user-images.githubusercontent.com/1636977/90249896-e0235680-de00-11ea-977c-8a8dc614a8bb.png)

Do I check the output location in the VS output Test window?

**Comment by aligneddev** [comment]
I had to check the box for Live Unit Testing and now they are being run!

![image](https://user-images.githubusercontent.com/1636977/90253538-e9172680-de06-11ea-9a9f-e2f403eee700.png)
