### ISSUE TITLE
Add support for R# 2021.1

### ISSUE THREAD

**Issue by robertcoltheart** [machine/machine.specifications#432]
Tracked here: https://github.com/machine/machine.specifications.runner.resharper/pull/153

**Comment by MrKevHunter** [comment]
We have an issue running the tests in a 4.7.2 class library.

To recreate using Rider 2021.1.2 and the plugin 2021.1.0 with a brand new class library

``` public class Calculator
    {
        public int Add(int x, int y)
        {
            return x + y;
        }
    }

    public class do_a_simple_sum
    {
        Establish context = () =>
        {
            SUT = new Calculator();
        };

        Because of = () =>
            result = SUT.Add(2,2);

        private It add_the_numbers = () =>
            result.ShouldEqual(4);

        private static Calculator SUT;
        private static int result;
    }
```
and the following packages installed
```
  <package id="Machine.Specifications" version="1.0.0" targetFramework="net472" />
  <package id="Machine.Specifications.Runner.VisualStudio" version="2.10.1" targetFramework="net472" />
  <package id="Machine.Specifications.Should" version="1.0.0" targetFramework="net472" />
  <package id="Mono.Cecil" version="0.10.0" targetFramework="net472" />
```
running tests causes them to return as inconclusive with the message 
```
mspectake2.do_a_simple_sum::add_the_numbers

Test not run

Last runner error: Could not load file or assembly 'JetBrains.ReSharper.TestRunner.Abstractions, Version=1.2.9.0, Culture=neutral, PublicKeyToken=5c492ec4f3eccde3' or one of its dependencies. The system cannot find the file specified., reason: System.IO.FileNotFoundException: Could not load file or assembly 'JetBrains.ReSharper.TestRunner.Abstractions, Version=1.2.9.0, Culture=neutral, PublicKeyToken=5c492ec4f3eccde3' or one of its dependencies. The system cannot find the file specified. File name: 'JetBrains.ReSharper.TestRunner.Abstractions, Version=1.2.9.0, Culture=neutral, PublicKeyToken=5c492ec4f3eccde3' at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes) at System.Reflection.RuntimeAssembly.GetExportedTypes() at JetBrains.ReSharper.TestRunner.Implementation.TestAdapterLoadContextFactoryFactory.RegisterDynamicScalars(ReflectionSerializersFacade facade) in C:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Merged\Implementation\ITestAdapterLoadContextFactory.cs:line 87 at JetBrains.ReSharper.TestRunner.Implementation.ClientEndpoint.<>c__DisplayClass4_1.<TryRegisterHandler>b__1() in C:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Core\Implementation\ClientEndpoint.cs:line 56 at System.Threading.Tasks.Task`1.InnerInvoke() at System.Threading.Tasks.Task.Execute() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at JetBrains.ReSharper.TestRunner.Implementation.ClientEndpoint.<RunAndLog>d__10.MoveNext() in C:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Core\Implementation\ClientEndpoint.cs:line 140 WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

--- EXCEPTION #1/2 [RdFault]
Message = “
  Could not load file or assembly 'JetBrains.ReSharper.TestRunner.Abstractions, Version=1.2.9.0, Culture=neutral, PublicKeyToken=5c492ec4f3eccde3' or one of its dependencies. The system cannot find the file specified., reason: System.IO.FileNotFoundException: Could not load file or assembly 'JetBrains.ReSharper.TestRunner.Abstractions, Version=1.2.9.0, Culture=neutral, PublicKeyToken=5c492ec4f3eccde3' or one of its dependencies. The system cannot find the file specified.
  File name: 'JetBrains.ReSharper.TestRunner.Abstractions, Version=1.2.9.0, Culture=neutral, PublicKeyToken=5c492ec4f3eccde3'
     at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
     at System.Reflection.RuntimeAssembly.GetExportedTypes()
     at JetBrains.ReSharper.TestRunner.Implementation.TestAdapterLoadContextFactoryFactory.RegisterDynamicScalars(ReflectionSerializersFacade facade) in C:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Merged\Implementation\ITestAdapterLoadContextFactory.cs:line 87
     at JetBrains.ReSharper.TestRunner.Implementation.ClientEndpoint.<>c__DisplayClass4_1.<TryRegisterHandler>b__1() in C:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Core\Implementation\ClientEndpoint.cs:line 56
     at System.Threading.Tasks.Task`1.InnerInvoke()
     at System.Threading.Tasks.Task.Execute()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at JetBrains.ReSharper.TestRunner.Implementation.ClientEndpoint.<RunAndLog>d__10.MoveNext() in C:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Core\Implementation\ClientEndpoint.cs:line 140
  
  WRN: Assembly binding logging is turned OFF.
  To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
  Note: There is some performance penalty associated with assembly bind failure logging.
  To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
”
ExceptionPath = Root.InnerException
ClassName = JetBrains.Rd.Tasks.RdFault
Data.ThreadLocalDebugInfo = “call `ServerSocket-<noname>.JetBrains.ReSharper.TestRunner.Abstractions.IClientEndpoint.SendMessage_proxy` (15325296026731086546)”
HResult = COR_E_EXCEPTION=80131500
Source = mscorlib
StackTraceString = “
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at JetBrains.ReSharper.UnitTestFramework.TestRunner.ServerMessageBroker.<SendMessage>d__2.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at JetBrains.ReSharper.UnitTestFramework.TestRunner.TestRunnerAgentManager.TestRunnerExecutionAgent.<<RunTests>b__8_2>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at JetBrains.ReSharper.UnitTestFramework.Extensions.TaskExtensions.<CancelIf>d__15.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at JetBrains.ReSharper.UnitTestFramework.Extensions.TaskExtensions.<ToEmptyTask>d__13.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at JetBrains.ReSharper.UnitTestFramework.Extensions.TaskExtensions.<ThrowIf>d__14`2.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at JetBrains.ReSharper.UnitTestFramework.TestRunner.TestRunnerAgentManager.BoundTestRunnerAgent.<RunSafe>d__11.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at JetBrains.ReSharper.UnitTestFramework.TestRunner.TestRunnerAgentManager.TestRunnerExecutionAgent.<RunTests>d__8.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at JetBrains.ReSharper.UnitTestFramework.TestRunner.TestRunnerRunStrategy.<Run>d__16.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at JetBrains.ReSharper.UnitTestFramework.Launch.UnitTestRun.<StartCore>d__33.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at JetBrains.Util.Special.GeneralUtil.WithNotNull[T](T item, Action`1 F)
     at JetBrains.ReSharper.UnitTestFramework.Launch.UnitTestRun.<StartCore>d__33.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at JetBrains.ReSharper.UnitTestFramework.Launch.UnitTestRun.<Start>d__32.MoveNext()
”

--- Outer ---

--- EXCEPTION #2/2 [LoggerException]
Message = “
  Could not load file or assembly 'JetBrains.ReSharper.TestRunner.Abstractions, Version=1.2.9.0, Culture=neutral, PublicKeyToken=5c492ec4f3eccde3' or one of its dependencies. The system cannot find the file specified., reason: System.IO.FileNotFoundException: Could not load file or assembly 'JetBrains.ReSharper.TestRunner.Abstractions, Version=1.2.9.0, Culture=neutral, PublicKeyToken=5c492ec4f3eccde3' or one of its dependencies. The system cannot find the file specified.
  File name: 'JetBrains.ReSharper.TestRunner.Abstractions, Version=1.2.9.0, Culture=neutral, PublicKeyToken=5c492ec4f3eccde3'
     at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
     at System.Reflection.RuntimeAssembly.GetExportedTypes()
     at JetBrains.ReSharper.TestRunner.Implementation.TestAdapterLoadContextFactoryFactory.RegisterDynamicScalars(ReflectionSerializersFacade facade) in C:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Merged\Implementation\ITestAdapterLoadContextFactory.cs:line 87
     at JetBrains.ReSharper.TestRunner.Implementation.ClientEndpoint.<>c__DisplayClass4_1.<TryRegisterHandler>b__1() in C:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Core\Implementation\ClientEndpoint.cs:line 56
     at System.Threading.Tasks.Task`1.InnerInvoke()
     at System.Threading.Tasks.Task.Execute()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at JetBrains.ReSharper.TestRunner.Implementation.ClientEndpoint.<RunAndLog>d__10.MoveNext() in C:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Core\Implementation\ClientEndpoint.cs:line 140
  
  WRN: Assembly binding logging is turned OFF.
  To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
  Note: There is some performance penalty associated with assembly bind failure logging.
  To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
InnerException = “Exception #1 at Root.InnerException”
HResult = COR_E_APPLICATION=80131600
StackTraceString = “
  at JetBrains.Util.ILoggerEx.LogException(ILogger this, LoggingLevel level, Exception exception, ExceptionOrigin exceptionOrigin, String comment)
     at JetBrains.Util.ILoggerEx.Error(ILogger this, Exception exception, ExceptionOrigin origin, String comment)
     at JetBrains.ReSharper.UnitTestFramework.Launch.UnitTestRun.<Start>d__32.MoveNext()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
     at System.Threading.Tasks.Task`1.TrySetException(Object exceptionObject)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception)
     at JetBrains.ReSharper.UnitTestFramework.Launch.UnitTestRun.<StartCore>d__33.MoveNext()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
     at System.Threading.Tasks.Task`1.TrySetException(Object exceptionObject)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception)
     at JetBrains.ReSharper.UnitTestFramework.TestRunner.TestRunnerRunStrategy.<Run>d__16.MoveNext()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
     at System.Threading.Tasks.Task`1.TrySetException(Object exceptionObject)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception)
     at JetBrains.ReSharper.UnitTestFramework.TestRunner.TestRunnerAgentManager.TestRunnerExecutionAgent.<RunTests>d__8.MoveNext()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
     at System.Threading.Tasks.Task`1.TrySetException(Object exceptionObject)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception)
     at JetBrains.ReSharper.UnitTestFramework.TestRunner.TestRunnerAgentManager.BoundTestRunnerAgent.<RunSafe>d__11.MoveNext()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
     at System.Threading.Tasks.Task`1.TrySetException(Object exceptionObject)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception)
     at JetBrains.ReSharper.UnitTestFramework.Extensions.TaskExtensions.<ThrowIf>d__14`2.MoveNext()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Threading.Tasks.TaskFactory.CompleteOnInvokePromise.Invoke(Task completingTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
     at System.Threading.Tasks.Task`1.TrySetException(Object exceptionObject)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception)
     at JetBrains.ReSharper.UnitTestFramework.Extensions.TaskExtensions.<ToEmptyTask>d__13.MoveNext()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
     at System.Threading.Tasks.Task`1.TrySetException(Object exceptionObject)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception)
     at JetBrains.ReSharper.UnitTestFramework.Extensions.TaskExtensions.<CancelIf>d__15.MoveNext()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Threading.Tasks.TaskFactory.CompleteOnInvokePromise.Invoke(Task completingTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
     at System.Threading.Tasks.Task`1.TrySetException(Object exceptionObject)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception)
     at JetBrains.ReSharper.UnitTestFramework.TestRunner.TestRunnerAgentManager.TestRunnerExecutionAgent.<<RunTests>b__8_2>d.MoveNext()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
     at System.Threading.Tasks.Task`1.TrySetException(Object exceptionObject)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception)
     at JetBrains.ReSharper.UnitTestFramework.TestRunner.ServerMessageBroker.<SendMessage>d__2.MoveNext()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
     at System.Threading.Tasks.Task`1.TrySetException(Object exceptionObject)
     at System.Threading.Tasks.TaskCompletionSource`1.TrySetException(Exception exception)
     at System.Threading.Tasks.TaskCompletionSource`1.SetException(Exception exception)
     at JetBrains.Collections.Viewable.SignalBase`1.Fire(T value)
     at JetBrains.Collections.Viewable.WriteOnceProperty`1.WriteOnceSignal.Fire(T value)
     at JetBrains.Collections.Viewable.WriteOnceProperty`1.SetIfEmpty(T newValue)
     at JetBrains.Rd.Tasks.WiredRdTask`2.CallSite.OnWireReceived(UnsafeReader reader)
     at JetBrains.Rd.Impl.MessageBroker.Execute(IRdWireable reactive, Byte[] msg)
     at JetBrains.Rd.Impl.MessageBroker.Dispatch(RdId id, Byte[] msg)
     at JetBrains.Diagnostics.LogEx.Catch(ILog log, Action action)
     at JetBrains.Rd.WireBase.Receive(Byte[] msg)
     at JetBrains.Rd.Impl.SocketWire.Base.ReadMsg()
     at JetBrains.Rd.Impl.SocketWire.Base.ReceiverProc(Socket socket)
     at JetBrains.Rd.Impl.SocketWire.Base.<>c__DisplayClass19_0.<.ctor>b__1(Socket socket)
     at JetBrains.Collections.Viewable.SignalBase`1.Fire(T value)
     at JetBrains.Collections.Viewable.ViewableProperty`1.set_Value(T value)
     at JetBrains.Rd.Impl.SocketWire.Server.<>c__DisplayClass4_0.<StartServerSocket>b__0()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.ThreadHelper.ThreadStart()
”


Last launch log file: C:\Users\KevHunter\AppData\Local\JetBrains\Rider2021.1\log\UnitTestLogs\Sessions\2021-04-29-09-03-41-127___731f39b2-07a9-4578-ad30-844027dc6e8d.log

```

**Comment by robertcoltheart** [comment]
Thanks, let me dig into it

**Comment by robertcoltheart** [comment]
Should be fixed here: https://github.com/machine/machine.specifications.runner.resharper/pull/160
