### ISSUE TITLE
Behaviors are broken in Resharper

### ISSUE THREAD

**Issue by mikeblakeuk** [machine/machine.specifications#459]
Using VS2022 17.0.2 with R# 2022.3 windows 10
(Also broken in rider)

![image](https://user-images.githubusercontent.com/1986660/148041246-1c99fcc2-3461-4b8b-8e39-9c173e523932.png)

Note, if you comment out //Behaves_like it appears to work.

System.InvalidCastException: Unable to cast object of type 'Machine.Specifications.Runner.ReSharper.Elements.MspecContextSpecificationTestElement' to type 'Machine.Specifications.Runner.ReSharper.Elements.MspecBehaviorSpecificationTestElement'.
   at Machine.Specifications.Runner.ReSharper.UnitTestElementFactory.GetOrCreateBehaviorSpecification(MspecBehaviorTestElement behavior, String fieldName, String ignoreReason)
   at Machine.Specifications.Runner.ReSharper.MspecTestMetadataExplorer.ExploreBehavior(MspecContextTestElement contextElement, IFieldInfo field)
   at Machine.Specifications.Runner.ReSharper.MspecTestMetadataExplorer.ExploreContext(ITypeInfo type)
   at Machine.Specifications.Runner.ReSharper.MspecTestMetadataExplorer.ExploreAssembly(IMetadataAssembly assembly, CancellationToken token)
   at JetBrains.ReSharper.UnitTestFramework.Exploration.Artifacts.MetadataElementsSource.ExploreProject(IProject project, FileSystemPath outputPath, MetadataLoader loader, ILogger logger, CancellationToken cancellationToken, Action`1 exploreAssembly)
   at Machine.Specifications.Runner.ReSharper.MspecTestExplorerFromMetadata.ProcessProject(MetadataLoader loader, IUnitTestElementObserver observer, CancellationToken token)
   at JetBrains.ReSharper.UnitTestFramework.Exploration.Artifacts.UnitTestExplorerFrom.Metadata.ProcessProjectCore(IUnitTestElementObserver observer, CancellationToken token)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at JetBrains.ReSharper.UnitTestFramework.Exploration.Artifacts.UnitTestExplorerFrom.DotNetArtifacts.Async.<ProcessArtifact>d__2.MoveNext()

**Comment by mikeblakeuk** [comment]
Hi Robert
Any more thoughts on this?

Thanks
mike

**Comment by robertcoltheart** [comment]
In progress here, feel free to subscribe for updates: https://github.com/machine/machine.specifications.runner.resharper/pull/198

**Comment by robertcoltheart** [comment]
This is fixed and released to the JB plugin marketplaces
