### ISSUE TITLE
Machine Specifications inconclusive in Rider 2021.3.2

### ISSUE THREAD

**Issue by sobrinth** [machine/machine.specifications#460]
In Rider 2021.3.2 with plugin version 2021.3.0 MSpecs are not run (inconclusive). Resharper.Testrunner was updated to version 2.6.2.0 in one of the updates for Rider 2021.3

```--- EXCEPTION #1/2 [RdFault]
Message = "
  Could not load file or assembly 'JetBrains.ReSharper.TestRunner.Abstractions, Version=2.6.1.0, Culture=neutral, PublicKeyToken=5c492ec4f3eccde3' or one of its dependencies. The system cannot find the file specified., reason: System.IO.FileNotFoundException: Could not load file or assembly 'JetBrains.ReSharper.TestRunner.Abstractions, Version=2.6.1.0, Culture=neutral, PublicKeyToken=5c492ec4f3eccde3' or one of its dependencies. The system cannot find the file specified.
  File name: 'JetBrains.ReSharper.TestRunner.Abstractions, Version=2.6.1.0, Culture=neutral, PublicKeyToken=5c492ec4f3eccde3'
     at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
     at System.Reflection.RuntimeAssembly.GetExportedTypes()
     at JetBrains.ReSharper.TestRunner.Implementation.TestAdapterLoadContextFactoryFactory.RegisterDynamicScalars(ReflectionSerializersFacade facade) in C:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Merged\Implementation\ITestAdapterLoadContextFactory.cs:line 87
     at JetBrains.ReSharper.TestRunner.Implementation.UnitTestRemoteAgent.Execute(RemoteAgentInitializationRequest request) in C:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Merged\Implementation\UnitTestRemoteAgent.cs:line 70
     at lambda_method(Closure , IAutoRegisterInProtocol )
     at JetBrains.ReSharper.TestRunner.Implementation.ClientEndpoint.<>c__DisplayClass4_1.<TryRegisterHandler>b__1() in C:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Core\Implementation\ClientEndpoint.cs:line 56
     at System.Threading.Tasks.Task`1.InnerInvoke()
     at System.Threading.Tasks.Task.Execute()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at JetBrains.ReSharper.TestRunner.Implementation.ClientEndpoint.<RunAndLog>d__10.MoveNext() in C:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Core\Implementation\ClientEndpoint.cs:line 140
  ```

**Comment by robertcoltheart** [comment]
Will take a look at this

**Comment by xiaoyvr** [comment]
Same issue here.

**Comment by MrKevHunter** [comment]
This appears to be fixed for me now, Thanks @robertcoltheart
