### ISSUE TITLE
Machine.Specifications for Rider does not work in version 2022.1.1

### ISSUE THREAD

**Issue by kamilbudziewski** [machine/machine.specifications#467]
Hi,
I'm using Rider 2022.1.1 and Machine.Specifications for Rider plugin version 2022.1.0 and when trying to run mspec tests I get:

```
Test not run

Last runner error: Cannot find 'Machine.Specifications.dll' controller type, reason: System.InvalidOperationException: Cannot find 'Machine.Specifications.dll' controller type Server stack trace: at Machine.Specifications.Runner.ReSharper.Adapters.Discovery.MspecController.GetControllerType() at Machine.Specifications.Runner.ReSharper.Adapters.Discovery.MspecController..ctor(TestRequest request, CancellationToken token) at Machine.Specifications.Runner.ReSharper.Adapters.MspecRunner.RunTests(TestRunRequest request, ITestDiscoverySink discoverySink, ITestExecutionSink executionSink) at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs) at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg) Exception rethrown at [0]: at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg) at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type) at JetBrains.ReSharper.TestRunner.Abstractions.ITestExecutor.RunTests(TestRunRequest request, ITestDiscoverySink discoverySink, ITestExecutionSink executionSink) at JetBrains.ReSharper.TestRunner.Implementation.UnitTestRemoteAgent.Execute(TestRunRequest request) in C:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Merged\Implementation\UnitTestRemoteAgent.cs:line 92 at JetBrains.ReSharper.TestRunner.Implementation.ClientEndpoint.<>c__DisplayClass4_1.<TryRegisterHandler>b__1() in C:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Core\Implementation\ClientEndpoint.cs:line 56 at System.Threading.Tasks.Task`1.InnerInvoke() at System.Threading.Tasks.Task.Execute() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at JetBrains.ReSharper.TestRunner.Implementation.ClientEndpoint.<RunAndLog>d__10.MoveNext() in C:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Core\Implementation\ClientEndpoint.cs:line 140

--- EXCEPTION #1/2 [RdFault]
Message = “
  Cannot find 'Machine.Specifications.dll' controller type, reason: System.InvalidOperationException: Cannot find 'Machine.Specifications.dll' controller type
  
  Server stack trace: 
     at Machine.Specifications.Runner.ReSharper.Adapters.Discovery.MspecController.GetControllerType()
     at Machine.Specifications.Runner.ReSharper.Adapters.Discovery.MspecController..ctor(TestRequest request, CancellationToken token)
     at Machine.Specifications.Runner.ReSharper.Adapters.MspecRunner.RunTests(TestRunRequest request, ITestDiscoverySink discoverySink, ITestExecutionSink executionSink)
     at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
     at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
  
  Exception rethrown at [0]: 
     at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
     at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
     at JetBrains.ReSharper.TestRunner.Abstractions.ITestExecutor.RunTests(TestRunRequest request, ITestDiscoverySink discoverySink, ITestExecutionSink executionSink)
     at JetBrains.ReSharper.TestRunner.Implementation.UnitTestRemoteAgent.Execute(TestRunRequest request) in C:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Merged\Implementation\UnitTestRemoteAgent.cs:line 92
     at JetBrains.ReSharper.TestRunner.Implementation.ClientEndpoint.<>c__DisplayClass4_1.<TryRegisterHandler>b__1() in C:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Core\Implementation\ClientEndpoint.cs:line 56
     at System.Threading.Tasks.Task`1.InnerInvoke()
     at System.Threading.Tasks.Task.Execute()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at JetBrains.ReSharper.TestRunner.Implementation.ClientEndpoint.<RunAndLog>d__10.MoveNext() in C:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Core\Implementation\ClientEndpoint.cs:line 140
”
ExceptionPath = Root.InnerException
ClassName = JetBrains.Rd.Tasks.RdFault
Data.ThreadLocalDebugInfo = “call `ServerSocket-<noname>.JetBrains.ReSharper.TestRunner.Abstractions.IClientEndpoint.SendMessage_proxy` (15325296026731086546)”
HResult = COR_E_EXCEPTION=80131500
Source = mscorlib
StackTraceString = “
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at JetBrains.ReSharper.UnitTestFramework.Execution.TestRunner.Activation.ServerMessageBroker.<SendMessage>d__2.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at JetBrains.ReSharper.UnitTestFramework.Execution.TestRunner.TestRunnerAgentManager.TestRunnerExecutionAgent.<<RunTests>b__8_1>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at JetBrains.ReSharper.UnitTestFramework.Common.Extensions.TaskExtensions.<CancelIf>d__15.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at JetBrains.ReSharper.UnitTestFramework.Common.Extensions.TaskExtensions.<ToEmptyTask>d__13.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at JetBrains.ReSharper.UnitTestFramework.Common.Extensions.TaskExtensions.<ThrowIf>d__14`2.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at JetBrains.ReSharper.UnitTestFramework.Execution.TestRunner.TestRunnerAgentManager.BoundTestRunnerAgent.<RunSafe>d__11.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at JetBrains.ReSharper.UnitTestFramework.Execution.TestRunner.TestRunnerAgentManager.TestRunnerExecutionAgent.<RunTests>d__8.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at JetBrains.ReSharper.UnitTestFramework.Execution.TestRunner.TestRunnerRunStrategy.<Run>d__17.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at JetBrains.ReSharper.UnitTestFramework.Execution.Launch.UnitTestRun.<StartCore>d__37.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at JetBrains.Util.Special.GeneralUtil.WithNotNull[T](T item, Action`1 F)
     at JetBrains.ReSharper.UnitTestFramework.Execution.Launch.UnitTestRun.<StartCore>d__37.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at JetBrains.ReSharper.UnitTestFramework.Execution.Launch.UnitTestRun.<Start>d__36.MoveNext()
”

--- Outer ---

--- EXCEPTION #2/2 [LoggerException]
Message = “
  Cannot find 'Machine.Specifications.dll' controller type, reason: System.InvalidOperationException: Cannot find 'Machine.Specifications.dll' controller type
  
  Server stack trace: 
     at Machine.Specifications.Runner.ReSharper.Adapters.Discovery.MspecController.GetControllerType()
     at Machine.Specifications.Runner.ReSharper.Adapters.Discovery.MspecController..ctor(TestRequest request, CancellationToken token)
     at Machine.Specifications.Runner.ReSharper.Adapters.MspecRunner.RunTests(TestRunRequest request, ITestDiscoverySink discoverySink, ITestExecutionSink executionSink)
     at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
     at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
  
  Exception rethrown at [0]: 
     at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
     at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
     at JetBrains.ReSharper.TestRunner.Abstractions.ITestExecutor.RunTests(TestRunRequest request, ITestDiscoverySink discoverySink, ITestExecutionSink executionSink)
     at JetBrains.ReSharper.TestRunner.Implementation.UnitTestRemoteAgent.Execute(TestRunRequest request) in C:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Merged\Implementation\UnitTestRemoteAgent.cs:line 92
     at JetBrains.ReSharper.TestRunner.Implementation.ClientEndpoint.<>c__DisplayClass4_1.<TryRegisterHandler>b__1() in C:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Core\Implementation\ClientEndpoint.cs:line 56
     at System.Threading.Tasks.Task`1.InnerInvoke()
     at System.Threading.Tasks.Task.Execute()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at JetBrains.ReSharper.TestRunner.Implementation.ClientEndpoint.<RunAndLog>d__10.MoveNext() in C:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Core\Implementation\ClientEndpoint.cs:line 140
”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
InnerException = “Exception #1 at Root.InnerException”
HResult = COR_E_APPLICATION=80131600
StackTraceString = “
  at JetBrains.Util.ILoggerEx.LogException(ILogger this, LoggingLevel level, Exception exception, ExceptionOrigin exceptionOrigin, String comment)
     at JetBrains.Util.ILoggerEx.Error(ILogger this, Exception exception, ExceptionOrigin origin, String comment)
     at JetBrains.ReSharper.UnitTestFramework.Execution.Launch.UnitTestRun.<Start>d__36.MoveNext()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
     at System.Threading.Tasks.Task`1.TrySetException(Object exceptionObject)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception)
     at JetBrains.ReSharper.UnitTestFramework.Execution.Launch.UnitTestRun.<StartCore>d__37.MoveNext()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
     at System.Threading.Tasks.Task`1.TrySetException(Object exceptionObject)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception)
     at JetBrains.ReSharper.UnitTestFramework.Execution.TestRunner.TestRunnerRunStrategy.<Run>d__17.MoveNext()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
     at System.Threading.Tasks.Task`1.TrySetException(Object exceptionObject)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception)
     at JetBrains.ReSharper.UnitTestFramework.Execution.TestRunner.TestRunnerAgentManager.TestRunnerExecutionAgent.<RunTests>d__8.MoveNext()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
     at System.Threading.Tasks.Task`1.TrySetException(Object exceptionObject)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception)
     at JetBrains.ReSharper.UnitTestFramework.Execution.TestRunner.TestRunnerAgentManager.BoundTestRunnerAgent.<RunSafe>d__11.MoveNext()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
     at System.Threading.Tasks.Task`1.TrySetException(Object exceptionObject)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception)
     at JetBrains.ReSharper.UnitTestFramework.Common.Extensions.TaskExtensions.<ThrowIf>d__14`2.MoveNext()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Threading.Tasks.TaskFactory.CompleteOnInvokePromise.Invoke(Task completingTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
     at System.Threading.Tasks.Task`1.TrySetException(Object exceptionObject)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception)
     at JetBrains.ReSharper.UnitTestFramework.Common.Extensions.TaskExtensions.<ToEmptyTask>d__13.MoveNext()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
     at System.Threading.Tasks.Task`1.TrySetException(Object exceptionObject)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception)
     at JetBrains.ReSharper.UnitTestFramework.Common.Extensions.TaskExtensions.<CancelIf>d__15.MoveNext()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Threading.Tasks.TaskFactory.CompleteOnInvokePromise.Invoke(Task completingTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
     at System.Threading.Tasks.Task`1.TrySetException(Object exceptionObject)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception)
     at JetBrains.ReSharper.UnitTestFramework.Execution.TestRunner.TestRunnerAgentManager.TestRunnerExecutionAgent.<<RunTests>b__8_1>d.MoveNext()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
     at System.Threading.Tasks.Task`1.TrySetException(Object exceptionObject)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception)
     at JetBrains.ReSharper.UnitTestFramework.Execution.TestRunner.Activation.ServerMessageBroker.<SendMessage>d__2.MoveNext()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
     at System.Threading.Tasks.Task`1.TrySetException(Object exceptionObject)
     at System.Threading.Tasks.TaskCompletionSource`1.TrySetException(Exception exception)
     at System.Threading.Tasks.TaskCompletionSource`1.SetException(Exception exception)
     at JetBrains.Collections.Viewable.SignalBase`1.Fire(T value)
     at JetBrains.Collections.Viewable.WriteOnceProperty`1.WriteOnceSignal.Fire(T value)
     at JetBrains.Collections.Viewable.WriteOnceProperty`1.SetIfEmpty(T newValue)
     at JetBrains.Rd.Tasks.WiredRdTask`2.CallSite.OnWireReceived(UnsafeReader reader)
     at JetBrains.Rd.Impl.MessageBroker.Execute(IRdWireable reactive, Byte[] msg)
     at JetBrains.Rd.Impl.MessageBroker.Dispatch(RdId id, Byte[] msg)
     at JetBrains.Diagnostics.LogEx.Catch(ILog log, Action action)
     at JetBrains.Rd.WireBase.Receive(Byte[] msg)
     at JetBrains.Rd.Impl.SocketWire.Base.ReadMsg()
     at JetBrains.Rd.Impl.SocketWire.Base.ReceiverProc(Socket socket)
     at JetBrains.Rd.Impl.SocketWire.Base.<>c__DisplayClass19_0.<.ctor>b__1(Socket socket)
     at JetBrains.Collections.Viewable.SignalBase`1.Fire(T value)
     at JetBrains.Collections.Viewable.ViewableProperty`1.set_Value(T value)
     at JetBrains.Rd.Impl.SocketWire.Server.<>c__DisplayClass4_0.<StartServerSocket>b__1()
     at JetBrains.Diagnostics.LogEx.Catch(ILog log, Action action)
     at JetBrains.Rd.Impl.SocketWire.Server.<>c__DisplayClass4_0.<StartServerSocket>b__0()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.ThreadHelper.ThreadStart()
”
```

Rollback to Rider 2021.3 helps

**Comment by robertcoltheart** [comment]
Can you share your csproj that you are using, or a cut-down version of it to show what framework, packages etc you have?

**Comment by mikeblakeuk** [comment]
Possible duplicate? of #466

**Comment by robertcoltheart** [comment]
Closing unless I get more information on this.
